import React, { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { api } from './api';

const initial = { name: '', rollNo: '', destination: '', reason: '' };
export default function StudentPortal() {
  const [form, setForm] = useState(initial); const [reference, setReference] = useState(null); const [pass, setPass] = useState(null); const [message, setMessage] = useState('');
  const submit = async (event) => { event.preventDefault(); setMessage(''); try { const response = await api.post('/api/outpass/request', form); setReference({ id: response.data.data.id, rollNo: form.rollNo }); setForm(initial); setMessage('Request sent. Keep your reference and check its status after HOD review.'); } catch (error) { setMessage(error.response?.data?.message || 'Could not submit the request.'); } };
  const checkStatus = async () => { if (!reference?.id || !reference?.rollNo) return; try { const response = await api.get(`/api/outpass/status/${reference.id}`, { params: { rollNo: reference.rollNo } }); setPass(response.data.data); setMessage(`Current status: ${response.data.data.status}`); } catch (error) { setMessage(error.response?.data?.message || 'Could not find this request.'); } };
  return <main className="page student-page"><header className="hero"><p className="eyebrow">Campus movement, simplified</p><h1>Request an outpass</h1><p>Share where you are going and why. Your approved digital pass is ready to scan at the gate.</p></header><section className="two-column"><form onSubmit={submit} className="card form-stack"><div className="section-title"><span className="icon-orb">↗</span><div><p className="eyebrow">Quick request</p><h2>Plan your exit</h2></div></div>{message && <div className="alert">{message}</div>}<label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Roll number<input required value={form.rollNo} onChange={(e) => setForm({ ...form, rollNo: e.target.value })} /></label><label>Destination<input required value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })} /></label><label>Reason<textarea required value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></label><button>Submit request <span>→</span></button></form><aside className="card status-card"><div className="section-title"><span className="icon-orb">▣</span><div><p className="eyebrow">Pass centre</p><h2>Your digital pass</h2></div></div><p>Keep the request reference to retrieve your approval and QR code.</p>{reference ? <><code>{reference.id}</code><label>Roll number<input value={reference.rollNo} onChange={(e) => setReference({ ...reference, rollNo: e.target.value })} /></label><button className="secondary" onClick={checkStatus}>Check approval status</button></> : <p className="muted">Your request reference appears here after submission.</p>}{pass?.qrToken && <div className="qr"><QRCodeSVG value={pass.qrToken} size={200} /><strong>Approved · show this QR code to the guard</strong><span>{pass.destination}</span></div>}{pass?.status === 'REJECTED' && <div className="alert error">Rejected: {pass.rejectNote}</div>}</aside></section></main>;
}
